In [3]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [22]:
# create a range array of 5
arr = np.arange(5)

In [24]:
# save the array
np.save('myarray.npy',arr)

In [31]:
# load same-named array as arr2
arr2 = arr

In [29]:
# create an array of the same name
arr = np.arange(0,10,2)

In [30]:
# load the original array as arr1
arr1 = np.load('myarray.npy')

In [52]:
# save arrays as a zip array
np.savez('zipped_arrays', y=arr2,x=arr1)

In [53]:
zipped_arrays = np.load('zipped_arrays.npz')

In [54]:
# call x elements of zipped array
zipped_arrays['x']

array([0, 1, 2, 3, 4])

In [55]:
# call y elements of zipped array
zipped_arrays['y']

array([0, 2, 4, 6, 8])

In [67]:
# save zipped array as a .txt file
np.savetxt('text_array.txt', arr1, delimiter=',')

In [66]:
# load array from txt file
np.loadtxt('text_array.txt')

array([0., 1., 2., 3., 4.])