In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [5]:
dframe = DataFrame(np.arange(16).reshape(4,4))

dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [9]:
blender = np.random.permutation(4)

In [10]:
blender

array([0, 3, 2, 1])

In [23]:
dframe.take(blender)

0   1   2   3
0   0   1   2   3
3  12  13  14  15
2   8   9  10  11
1   4   5   6   7

In [25]:
# first construct an array of 3 elements
box = np.array([1,2,3])

In [32]:
# generate list of integers from 0 to 2, selected at random
shaker = np.random.randint(0,len(box),size=10)

In [33]:
shaker

array([1, 0, 2, 1, 2, 1, 0, 1, 0, 0])

In [34]:
hand_grabs = box.take(shaker)

hand_grabs

array([2, 1, 3, 2, 3, 2, 1, 2, 1, 1])

In [38]:
box.take([0,1,1])

array([1, 2, 2])