In [2]:
import numpy

In [4]:
my_list = [1,2,3,4]

In [6]:
my_array = numpy.array(my_list)

In [8]:
my_list2 = [11,22,33,44]

In [11]:
my_lists = [my_list, my_list2]

In [14]:
# creating an array of arrays

my_array2 = numpy.array(my_lists)

In [22]:
# inspecting the shape of the array

my_array2.shape

(2, 4)

In [33]:
# get the datatype of the array

my_array2.dtype

dtype('int32')

In [36]:
# construct a 1-dim array of 5 zeros
numpy.zeros(5)

array([0., 0., 0., 0., 0.])

In [41]:
# construct a 5x5 array of zeros

numpy.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
# construct an identity matrix

numpy.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
# create a 1-dim 'range' array 
numpy.arange(5)

array([0, 1, 2, 3, 4])

In [52]:
# create a 1-dim 'range' array with irregular spacing
numpy.arange(0, 50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])