In [10]:
import numpy as np

In [13]:
# create a 2-dim array

my_array = np.array([[1,2,3,4],[5,6,7,8]])

In [16]:
# multiply array with itself

my_array * my_array

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [19]:
# subtract array from itself

my_array - my_array

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [20]:
# divide 1 by the array

1/my_array

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [21]:
# take array to the power of 3

my_array**3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]], dtype=int32)